## Aufgabe Konfidenzintervall : $\mu \pm \sigma$
Berechnen Sie für die Grundgesamtheit der Menge {$10, 20, \dots, 990 , 1000$} Mittelwert $\mu$ und Standardabweichung $\sigma$. Nehmen Sie 100 zufällige Stichproben von 5 Elementen und berechnen deren Mittelwert $\mu_{\bar{x}}$. <br> Wieviele Prozent der Stichprobenmittelwerte liegen im Intervall $\mu \pm \sigma_{\bar{x}}$ ?

## Lösung :

In [1]:
import numpy as np

a=list(range(10,1010,10))
b=[]
mean_pop= np.mean(a)
std_pop= np.std(a)
std_sample = std_pop/(5)**(1/2)
low = mean_pop - std_sample
high = mean_pop + std_sample
print(a)
#print(low , 'low')
#print(high , 'high')
print(mean_pop, ': Mittelwert der Grundgesamtheit')
print(std_pop, ': Standardabweichung der Grundgesamtheit')
print(std_sample, ': Standardabweichung des Stichprobenmittels')



for i in range(1,101):
    my_sample_10 = np.random.choice(a , size=5)
    print(my_sample_10,'=',np.mean(my_sample_10))
    if np.mean(my_sample_10) < low :
        print('too low')
    elif np.mean(my_sample_10) > high :
        print('too high')
    else : b.append(np.mean(my_sample_10))
print(b)
#Prozent der Werte innerhalb des Intervalls
frequency=len(b)/100
print(frequency*100 , 'Prozent der Werte liegen innerhalb einer Standardabweichung' )

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 1000]
505.0 : Mittelwert der Grundgesamtheit
288.66070047722116 : Standardabweichung der Grundgesamtheit
129.0929897399545 : Standardabweichung des Stichprobenmittels
[240 770 560 260  40] = 374.0
too low
[490 220 120  30 850] = 342.0
too low
[ 40 230 120 470 340] = 240.0
too low
[490 610 850 150 420] = 504.0
[540  60 280 320 680] = 376.0
[390 860 990 150 280] = 534.0
[540 930 860 450 550] = 666.0
too high
[480 400 460 490 770] = 520.0
[470 380 420 990 440] = 540.0
[100 330 780 760 320] = 458.0
[980 790 660 